### ISSUE TITLE
[demo] Add a way to crash the application

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#347] opened 2024-05-07 22:09 UTC
Not sure where to put it, but could be nice to have a menu item or a button on a fragment in the shop activity that causes the app to crash. This allows us to manually test the crash detection instrumentation.

For starters, we can just pick whatever crash mechanism we like and if we want to try other ways in the future we can do that.

**Comment by marandaneto** [comment] 2024-05-08 07:46
shake to break it :D

**Comment by magda-woj** [comment] 2024-09-04 20:32
hi @breedx-splk assign this to me

**Comment by bidetofevil** [comment] 2024-09-10 23:43
It would be nice to track both JVM crashes and process terminations caused by the native layer - or something that simulates OS termination

**Closed** 2024-09-12 17:10 UTC
Labels: help wanted, demo-app

**Comment by breedx-splk** [comment] 2024-09-12 18:10
@bidetofevil this got auto-closed when #584 was merged. If you feel strongly about the native bits, can you open a new issue for that? I'd also appreciate some clever ideas on how to simulate that. 😁

**Comment by bidetofevil** [comment] 2024-09-17 15:00
Will do!
